### ISSUE TITLE
Recaptcha in controller of web api

### ISSUE THREAD

**Issue by aldeng11** [maliming/reCAPTCHA#8]
The examples show the recaptcha implemented as a service that takes an IConfiguration, which is great for DI, but not my application.

I have a web api that serves many domains, and each account has recaptcha credentials. I validate the recaptcha in a controller.

How do I accomplish this? I thought of instantiating a local IConfigruation, but the process looks awkward and overly complex.

**Comment by maliming** [comment]
hi

I don’t quite understand your needs, can you give me an example? Please share some code if you can.

**Comment by muhlisatac** [comment]
Same problem here. I want to resolve tenants from domain instead of sub-domain. So I have recaptcha configuration from google for every new domain. But in startup I cant be able to get domain name of the current context to be able to read sitekey and secretkey of that tenant from appsettings. By the way im using anz.

**Comment by maliming** [comment]
hi @scorpion86 

You can refer to this to make reCAPTCHA support multi-tenants.

https://medium.com/volosoft/asp-net-core-3-1-social-login-settings-by-tenant-efaa2d5af921
